language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "sudo apt-get update"
  - "sudo apt-get install python-numpy python-scipy gfortran"
  - "pip install numpy"
  - "python setup.py install"
script:
  - "cd examples ; make test"
notifications:
  email:
    - james.kermode@gmail.com
